---

- name: install epel
  yum:
    name: epel-release
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: daemon off in config
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "daemon off"
    line: "daemon off;"
