- hosts: all
  gather_facts: false
- hosts: 
    - ren
    - stimpy
  roles:
    - role: nginx-install
- hosts: 
    - ren
  roles:
    - role: ren-html
- hosts: 
    - ren
    - stimpy
  roles:
    - role: stimpy-html

